name = "HORIZONSAPI"
uuid = "43f16097-e9b8-4cdf-b85c-17835d4869de"
authors = ["Joe Carpinelli <jdcarpinelli@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[extras]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
